### PR TITLE
Landing page FAQ & Instructions 

### PR DESCRIPTION
**Pull request by o-bm**
Added top right button to show the information about UML mentor

image

and button for instructions
image

### CODE REVIEW

**Comment by o-bm** [comment]
close #50

**Comment by o-bm** [comment]
here is the raw data if anyone wants to review 
## 1. Introduction to Software Architecture

Software architecture plays a critical role in the development of robust and scalable applications. By understanding the foundational elements, students can build more efficient and maintainable systems.

## 2. What is UML Mentor?

UML Mentor is a collaborative learning platform that offers a unique approach to mastering software design through practical challenges, peer feedback, and a supportive community.

## 3. Getting Started with UML Mentor

To start, visit the UML Mentor website and log in using shibboleth. Familiarize yourself with the dashboard to access challenges, view your points, and participate in the community.

## 4. Browsing Challenges

Challenges on UML Mentor cover a range of topics and difficulties. They're designed to test your application of design patterns and principles in creating UML diagrams. Select a challenge that aligns with your interests or areas you wish to improve. 

## 6. Submitting Solutions

Provide your solution by uploading a UML diagram and accompanying description. Ensure that your submissions are thorough and reflect the challenge requirements. You can also use the built in editor to create your solutions !

## 7. UML Diagrams and Design Principles

Your solutions will be based on UML diagrams, which are a critical aspect of software design. They help visualize the structure and behavior of systems.

## 8. Understanding the Points System

Points are awarded based on the complexity of the challenge difficulty. They serve as a metric for your growth and contributions to the community.
10 points are for easy questions
20 points are for medium questions
30 points for hard questions
The difficulty level is indicated by the number of stars next to a challenge. The more stars, the more difficult.

## 9. Community Feedback and Interaction

Engage with solutions posted by others by commenting and discussing different approaches. Useful feedback is incentivized with points, encouraging a helpful community. You will earn 20 points by providing feedback to your peers !

## 10. Managing Your Submissions

You can view and manage your submissions from your profile. Edit, delete, or update your solutions as needed.

## 12. Achievements and Leaderboards

Unlock achievements as you progress and climb the leaderboards by actively participating and excelling in challenges.

## 13. Data Privacy and User Conduct
Anything you upload to UML Mentor will be visible to the instructors and TAs of the course, however, your uploads will not be used for grading. 

## 14. Contact and Support
- Omar Khamis: omar.khamis@mail.utoronto.ca
- Vlad Yaremchuk: vlad@mail.utoronto.ca
- Alex Apostolu: alex@mail.utoronto.ca
- Eren Suner: eren@mail.utoronto.ca

## 15. Credits and Acknowledgements

UML Mentor is made possible by the dedicated efforts of our team:
Faculty Supervisor:
Rutwa Engineer
Mentors: 
Arthur 
Developers:
Omar Khamis
- Vlad Yaremchuk
- Alex Apostolu
- Eren Suner

**Comment by arthurhohinng** [comment]
Need to rebase

**Comment by Vladmidir** [comment]
I don't like the instructions button being with the other three buttons. In my opinion, we should probably add an info icon (e.g. top right corner of the header).

**Comment by o-bm** [comment]
> I don't like the instructions button being with the other three buttons. In my opinion, we should probably add an info icon (e.g. top right corner of the header).

I think it will be clearer to have it within these three buttons. I will rearrange them because I think to make instructions be the last button

**Pull request merged**
