### PR TITLE
Import JSON to db

### LINKED ISSUE #22: Write the JSON file into the DB
Make a script for writing the JSON file containing challenges into the SQL database. (Make a new JS file that exports the object in `challenges.json`, import that object into the script file). 

Map 
- title to title
- id to id
- difficulty to difficulty
- (outcome + key patterns + general description + usage scenarios) are to be made into a JS object, converted to string and put in the `description` column as text. Upon retrieval, we convert the json string back to js object.

### PR DESCRIPTION
**Pull request by Vladmidir**
## Notes
- Also implemented challenge data fetching for Challenge page.
- Future incorporation of completion status for challenges depending on the user in the session is needed.

close #22

### CODE REVIEW

**Comment by o-bm** [comment]
A more descriptive description would be much appreciated.

**Comment by o-bm** [comment]
db.sequelize.sync({ force: true, logging: false}).then(async () => { // Use { force: true } cautiously as it will drop existing tables

I am using this is just for developing/testing purposes correct?

**Comment by o-bm** [comment]
you mentioned the server now runs from the root directory. is it same for the client as well? do they run concurrently ?

**Comment by o-bm** [comment]
Also, for keyPatterns field in the JSON I am assuming that it is the key patterns related to a challenge e.g a challenge could focus on the visitor pattern or factory pattern etc.. would it be better to have a list for that field because a challenge may have several key patterns. also to keep it standardized we could have only the name of the pattern and not a description 

"keyPatterns": ["Factory Method pattern for creating different types of blog posts."],

**Review by o-bm — COMMENTED** [review]
Looks good. I added comments in the PR.

**Comment by Vladmidir** [comment]
> A more descriptive description would be much appreciated.

I find the code self explanatory. That said, we can discuss documentation in the next meeting.

**Comment by Vladmidir** [comment]
> much

It wipes the database I am pretty sure. So if you restart the server in production with `force: true`, it will delete all of people's data. Including all the solutions and user accounts.

**Comment by Vladmidir** [comment]
> you mentioned the server now runs from the root directory. is it same for the client as well? do they run concurrently ?

You run the server commands from the root directory. The client commands are still run from the client directory. I can explain in more details in the meeting, so that everyone is on board.

**Comment by Vladmidir** [comment]
> Also, for keyPatterns field in the JSON I am assuming that it is the key patterns related to a challenge e.g a challenge could focus on the visitor pattern or factory pattern etc.. would it be better to have a list for that field because a challenge may have several key patterns. also to keep it standardized we could have only the name of the pattern and not a description
> 
> "keyPatterns": ["Factory Method pattern for creating different types of blog posts."],

It is a list as of right now. We can discuss the formatting in the meeting. It is possible to add just the list of design patterns without the descriptions as an *additional* field.

**Pull request merged**
